spring.application.name=springbootv3
# Konfiguracja bazy danych H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Konfiguracja JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (dost?pna na /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Port aplikacji
server.port=8080

# Logowanie
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

#spring.jpa.hibernate.ddl-auto=create-drop